### PR TITLE
License header update, #171

### PR DESCRIPTION
**Pull request by srbala**
Fix to issue #171

### CODE REVIEW

**Comment by decebals** [comment]
My script says that one file is not modified (101 instead of 102).
The file that is missing is `./pf4j/src/test/java/org/pf4j/PluginDependencyTest.java`.

```bash
$ find . -name *.java -exec grep "Copyright" {} \; | wc -l
102

$ find . -name *.java -print -exec grep "Copyright" {} \;
./pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ServiceProviderExtensionFinder.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/CompoundPluginLoader.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultVersionManager.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultExtensionFinder.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/LoggingPluginStateListener.java
 * Copyright 2018 Decebal Suiu
./pf4j/src/main/java/org/pf4j/VersionManager.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/main/java/org/pf4j/CompoundPluginRepository.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginDependency.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginRepository.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DevelopmentPluginClasspath.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginLoader.java
 * Copyright 2016 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ExtensionFinder.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ExtensionDescriptor.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginStatusProvider.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PropertiesPluginDescriptorFinder.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginException.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginStateListener.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginDescriptorFinder.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ExtensionFactory.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginState.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginStatusProvider.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ExtensionPoint.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/CompoundPluginDescriptorFinder.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginManager.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ExtensionWrapper.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
 * Copyright 2016 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginFactory.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/RuntimeMode.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/processor/ServiceProviderExtensionStorage.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/processor/ExtensionStorage.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/processor/LegacyExtensionStorage.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginLoader.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/BasePluginRepository.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginWrapper.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginDescriptor.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/JarPluginRepository.java
 * Copyright 2016 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginDescriptor.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginFactory.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginRepository.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultExtensionFactory.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/DirectedGraph.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/NameFileFilter.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/NotFileFilter.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/JarFileFilter.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/HiddenFilter.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/OrFileFilter.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/DirectoryFileFilter.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/FileUtils.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/ClassUtils.java
 * Copyright 2016 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/StringUtils.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/ExtensionFileFilter.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/Unzip.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/AndFileFilter.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/util/ZipFileFilter.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DependencyResolver.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/JarPluginLoader.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginClasspath.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginStateEvent.java
 * Copyright 2014 Decebal Suiu
./pf4j/src/main/java/org/pf4j/ManifestPluginDescriptorFinder.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginManager.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/Plugin.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/PluginClassLoader.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/main/java/org/pf4j/LegacyExtensionFinder.java
 * Copyright 2013 Decebal Suiu
./pf4j/src/main/java/org/pf4j/DefaultPluginClasspath.java
 * Copyright 2016 Decebal Suiu
./pf4j/src/main/java/org/pf4j/Extension.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/test/java/org/pf4j/ManifestPluginDescriptorFinderTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/AbstractExtensionFinderTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultExtensionFactoryTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultPluginStatusProviderTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DependencyResolverTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/CompoundPluginDescriptorFinderTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/LoadPluginsTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/ExtensionAnnotationProcessorTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultVersionManagerTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultPluginRepositoryTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultPluginManagerTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/LegacyExtensionStorageTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/processor/ServiceProviderExtensionStorageTest.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/TestExtension.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/TestExtensionPoint.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/FailTestPlugin.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/AnotherFailTestPlugin.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/TestPlugin.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/FailTestExtension.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/plugin/PluginZip.java
 * Copyright 2015 Decebal Suiu
./pf4j/src/test/java/org/pf4j/PluginDependencyTest.java
 * Copyright 2015 Mario Franco.
./pf4j/src/test/java/org/pf4j/util/FileUtilsTest.java
 * Copyright 2017 Decebal Suiu
./pf4j/src/test/java/org/pf4j/PropertiesPluginDescriptorFinderTest.java
 * Copyright 2012 Decebal Suiu
./pf4j/src/test/java/org/pf4j/DefaultPluginFactoryTest.java
 * Copyright 2015 Decebal Suiu
./demo_gradle/api/src/main/java/org/pf4j/demo/api/Greeting.java
 * Copyright 2012 Decebal Suiu
./demo_gradle/app/src/main/java/org/pf4j/demo/Boot.java
 * Copyright 2012 Decebal Suiu
./demo_gradle/app/src/main/java/org/pf4j/demo/WhazzupGreeting.java
 * Copyright 2014 Decebal Suiu
./demo_gradle/plugins/plugin2/src/main/java/org/pf4j/demo/hello/HelloPlugin.java
 * Copyright 2012 Decebal Suiu
./demo_gradle/plugins/plugin1/src/main/java/org/pf4j/demo/welcome/WelcomePlugin.java
 * Copyright 2012 Decebal Suiu
./demo/api/src/main/java/org/pf4j/demo/api/Greeting.java
 * Copyright 2012 Decebal Suiu
./demo/app/src/main/java/org/pf4j/demo/Boot.java
 * Copyright 2012 Decebal Suiu
./demo/app/src/main/java/org/pf4j/demo/HowdyGreeting.java
 * Copyright 2015 Decebal Suiu
./demo/app/src/main/java/org/pf4j/demo/WhazzupGreeting.java
 * Copyright 2014 Decebal Suiu
./demo/plugins/plugin2/src/main/java/org/pf4j/demo/hello/HelloPlugin.java
 * Copyright 2012 Decebal Suiu
./demo/plugins/plugin1/src/main/java/org/pf4j/demo/welcome/WelcomePlugin.java
 * Copyright 2012 Decebal Suiu
```

**Comment by srbala** [comment]
Good find, odd man is below. Fixed that one too.

```
./pf4j/src/test/java/org/pf4j/PluginDependencyTest.java
 * Copyright 2015 Mario Franco.
```

**Comment by decebals** [comment]
Thanks!

**Comment by srbala** [comment]
Thank you.

**Pull request merged**
