### PR TITLE
Recreate file system windows exception

### PR DESCRIPTION
**Pull request by hazemkmammu**
Recreates FileSystemException in windows on plugin delete

### CODE REVIEW

**Comment by decebals** [comment]
Thanks!
I will make some modifications to your code, I will test it and I will come with a response asap.

**Comment by hazemkmammu** [comment]
Thanks

**Comment by decebals** [comment]
I can confirm that your test replicate the problem:

image

image

@hazemkmammu 
Now, that the problem is replicable on Windows, can you add the fix as a new PR? Thanks!

**Comment by hazemkmammu** [comment]
@decebals Please see #322

**Pull request merged**
