### PR TITLE
Update module-info.java

### LINKED ISSUE #405: Java 9 - module-info problems
Since using Java 9 with module-info, I cannot build the project anymore.

I can install the current master with maven on command-line, but I cannot build the project in Intellij Idea due to unknown module-info files.

When I change the line https://github.com/pf4j/pf4j/blob/master/pom.xml#L46 from version 8 to 9 (which would be the correct value IMHO), I can build in Idea, but not on the command-line anymore.

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pf4j: Compilation failure: Compilation failure:
...module-info.java:[30,27] module not found: org.objectweb.asm
...module-info.java:[36,19] module not found: slf4j.api
...module-info.java:[41,18] module not found: java.semver
```
The unit-tests have strange NoClassDefFound errors and duplicate resource-loading problems.

I think something regarding the Java Modules is not set-up correctly.
Or maybe I am doing something wrong?

### PR DESCRIPTION
**Pull request by decebals**
Try to fix https://github.com/pf4j/pf4j/issues/405.

### CODE REVIEW

**Comment by decebals** [comment]
The remaining problem is related to https://github.com/zafarkhaja/jsemver.

**Comment by RationalityFrontline** [comment]
Please use "requires static" with "org.objectweb.asm", or end users will be forced to explicitly declare an additional dependency of asm besides pf4j itself (this is mentioned in the issue #405 by @drinkitup777).

**Comment by decebals** [comment]
> The remaining problem is related to https://github.com/zafarkhaja/jsemver.

For this reason I converted this PR in a draft.

**Comment by decebals** [comment]
The part with jsemver remains unsolved (see https://github.com/pf4j/pf4j/pull/426#issuecomment-803242211) but I think that the direction is good.

**Pull request merged**
