### PR TITLE
release file stream when read properties, the origin code cause the p…

### PR DESCRIPTION
**Pull request by yeahCaesar**
…roblem that we can't delete jar file after unloading plugin with defaultPluginManager

### CODE REVIEW

**Comment by yeahCaesar** [comment]
@decebals

**Comment by decebals** [comment]
Unfortunately I cannot reproduce the problem (via `JarPluginManagerTest#deletePlugin`):
image
I think that this is because the plugin jar file from the unit test doesn't contain classes (only metadata).
Did you tested on your application that this PR fixes the problem?
I will try to see if I can find a possibility to add a unit test that replicates the problem.

**Comment by decebals** [comment]
Nothing until now:
image

**Comment by decebals** [comment]
Tried with a new unit test that simulate exactly your unit test described in #355 but I cannot replicate the problem:
image
image
image

So, again I cannot replicate the problem.

**Comment by yeahCaesar** [comment]
image
Of course I test the modification with my local environment,  the modification resolves my problem.
As a said before, JarPluginManager is Ok , the problem occured when I use defaultPluginManager to load and start the plugin(a jar file). The defaultPluginManager tries to read properties with Proproties first while the jarPluginManager only uses the Manifest. Let me make a simple unit test to replicate the problem for you.

**Comment by yeahCaesar** [comment]
` @Test
    public void deleteTest(){
        PluginManager pluginManager = new DefaultPluginManager();
        Path path = Paths.get(jarFile);
        pluginManager.loadPlugin(path);
        pluginManager.startPlugin(pluginName);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        boolean deleted = pluginManager.deletePlugin(pluginName);
        //boolean delete = FileUtil.deleteDirHarder(path.toFile());
        System.out.println("delete result::"+deleted);
        File file = new File(jarFile);
        if(!file.exists()){
            try {
                boolean canCreateNewFile = file.createNewFile();
                assert canCreateNewFile;
            } catch (IOException e) {
                System.out.println("could not create the file which should be deleted with calling pluginManager.deletePlugin");
                assert false;
                e.printStackTrace();
            }
        }
    }`
the above code output:
deleteFail
you can see, the file.exist( ) return false, but create a file with the same name is false.Replacing DefaultPluginManager with JarPluginManage,the UT will be successful.
image
@decebals

**Comment by decebals** [comment]
@yeahCaesar 
Thanks for clarification and patience!
I will try to run the same tests with `DefaultPluginManger` instead of `JarPluginManager` and I will come with news asap.

**Comment by decebals** [comment]
The d359ad77ac654883db56cf9376df9b2a98c18ff9 commit added two unit tests in `DefaultPluginManager`. The `deleteJarPlugin` test replicates our problem. 
It's not clear for me why `JarManagerTest#deletePlugin` doesn't replicate the problem.

**Comment by decebals** [comment]
In the end I preferred to close the `FileSystem` only for jar files, it's more safe (I am not confident that the file system should be close in any circumstances).
Please verify the patch.
Thanks for help!

**Pull request closed without merging**
