### PR TITLE
Only call `stopPlugin` during unload if the plugin is started

### PR DESCRIPTION
**Pull request by slovdahl**
Related to #459.

### CODE REVIEW

**Comment by slovdahl** [comment]
Unrelated to this PR, but I just noticed it at the same time.

```java
public abstract class AbstractPluginManager implements PluginManager {

    // ...

    protected boolean unloadPlugin(String pluginId, boolean unloadDependents) {
        try {
            if (unloadDependents) {
                List<String> dependents = dependencyResolver.getDependents(pluginId);
                while (!dependents.isEmpty()) {
                    String dependent = dependents.remove(0);
                    unloadPlugin(dependent, false);
                    dependents.addAll(0, dependencyResolver.getDependents(dependent));
                }
            }
        }

        // ...
    }
}
```

Is there a reason `unloadPlugin(dependent, false)` is called with `false` as the second parameter? To me, it would somehow feel more natural to use `true`, to make sure that the whole chain of dependant plugins are unloaded first.

**Comment by decebals** [comment]
@slovdahl 
I simply forgot to answer this issue. Sorry.
I think that we need some tests here.
In my opinion the problem is in [AbstractPluginManager#stopPlugin](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L451). We need to stop a plugin only if it is in STARTED state. Method AbstractPluginManager#stopPlugin should check the state.

> Is there a reason unloadPlugin(dependent, false) is called with false as the second parameter? To me, it would somehow feel more natural to use true, to make sure that the whole chain of dependant plugins are unloaded first.

It's a good question and we need to check the impact of this change.

Also, we need to add more tests for AbstractPluginManager, to cover more cases (transitions from one state to another).

**Comment by perlun** [comment]
@slovdahl - should we also try to include this change? In `unloadPlugin()`, right before the`firePluginStateEvent()` call (could unfortunately not make it a suggestion here in the MR because of GitHub limitations): 

```java
// Differs from the pf4j 3.6.0 superclass: clean up the unresolved plugins state,
// otherwise loading the same plugin again might not succeed.
getUnresolvedPlugins().remove( pluginWrapper );
```

**Comment by slovdahl** [comment]
> @slovdahl - should we also try to include this change from our version of the class? In `unloadPlugin()`, right before the`firePluginStateEvent()` call (could unfortunately not make it a suggestion here in the MR because of GitHub limitations):
> 
> ```java
> // Differs from the pf4j 3.6.0 superclass: clean up the unresolved plugins state,
> // otherwise loading the same plugin again might not succeed.
> getUnresolvedPlugins().remove( pluginWrapper );
> ```

It's probably out of scope in this PR, I wrote a test in #558 and aim for fixing the relevant problems there. I think this is one of them.

**Comment by slovdahl** [comment]
Also looks like #521 by @decebals is a much more complete fix than my suggestion here.

**Comment by decebals** [comment]
@slovdahl I tested your test from this PR with #521 and it passes.

**Comment by slovdahl** [comment]
@decebals Nice :+1: Feel free to pull in the test from this PR in #521, and we can close this.

**Comment by decebals** [comment]
@perlun Can you test the fix (available on master already and available as 3.11.0-SNAPSHOT)?

My intention is to release a new version after #564 will be merged.

**Comment by perlun** [comment]
Sounds good @decebals, I'll make sure that either me or @slovdahl tests the 3.11.0-SNAPSHOT version. Does it include the https://github.com/pf4j/pf4j/pull/567 fix too? If so, that would be super-great. :bow:

**Comment by decebals** [comment]
I [uploaded](https://oss.sonatype.org/content/repositories/snapshots/org/pf4j/pf4j/3.11.0-SNAPSHOT/) the latest SNAPSHOT version (it contains what it's on master - included #567).
If your tests go well, I can release a new version.

**Comment by decebals** [comment]
> I [uploaded](https://oss.sonatype.org/content/repositories/snapshots/org/pf4j/pf4j/3.11.0-SNAPSHOT/) the latest SNAPSHOT version (it contains what it's on master - included #567).
> If your tests go well, I can release a new version.

@slovdahl @perlun How are your tests going? I need a good result to make the release.
​

**Comment by slovdahl** [comment]
@decebals I'm sorry for keeping you waiting here, I haven't been able to prioritize this the past weeks. Today I finally have a bit of time.

I'm doing some testing as we speak, but I found some issues on our side that I need to investigate and fix before I can test all our use-cases. But it looks like we can remove all of our duplication of the `AbstractPluginManager` methods and use `PluginStateListener` instead :+1: :partying_face:

**Comment by slovdahl** [comment]
Finally got the issues sorted out. Everything seems to work great, so as far as I'm concerned, feel free to put out a new release :slightly_smiling_face: Thanks a lot for the all work on this, greatly appreciated! :bow:

**Pull request closed without merging**
