### PR TITLE
Implement PluginClassLoader.getResources (#336)

### PR DESCRIPTION
**Pull request by slovdahl**
The logic of the method is essentially a reversed copy & paste of the
`ClassLoader::getResources(String)` method.

See #336 for a more in-depth description of the problem this PR tries to resolve.

### CODE REVIEW

**Comment by slovdahl** [comment]
I took the liberty to write some tests for the existing `getResource(String)` method as well, mainly to validate my assumptions about how it works.

I'd be happy to add more tests if I've missed some (edge-)cases.

**Comment by decebals** [comment]
It looks good.
I prefer to use [PluginZip](https://github.com/pf4j/pf4j/blob/master/pf4j/src/test/java/org/pf4j/plugin/PluginZip.java) and [PluginJar](https://github.com/pf4j/pf4j/blob/master/pf4j/src/test/java/org/pf4j/plugin/PluginJar.java) in tests. These classes (PluginZip and PluginJar) is not finished yet (missing support for add files - classes, jars, resources) but they can be improved relative easy.
If you have few time, please take a look to see if you can use one of these classes.
The PR is very good and it will be merged in the end. Thanks!

**Comment by slovdahl** [comment]
Thank you for the feedback, and sorry for the late response.

I'm trying to figure out how to utilize `PluginZip` in the test. I have added a `PluginZip.Builder` method for adding files to the archive, but it's not obviously clear to me how e.g. unzip the archive. I see that e.g. `LoadPluginsTest` uses `PluginManager::loadPluginFromPath` for unzipping it, but it feels like using that class in the test turns it more into an integration test than unit test. What are your thoughts about it?

**Comment by slovdahl** [comment]
Thanks for the rubberduck.. :duck: :smile: I think I found a solution that feels ok. I'll let the latest changes be a separate commit until you have reviewed them.

**Comment by decebals** [comment]
I missed the notification that you made some changes. Sorry.
Your PR is awesome. I like the improvements to `PluginZip` (the `addFile` methods).
In the context of your second commit, do you think that we need the files added by you in `resources` in the first commit? 
I think that we can generate these files on the fly (this was the main idea when I started to implement `PluginZip` and `PluginJar`).

**Comment by slovdahl** [comment]
>  In the context of your second commit, do you think that we need the files added by you in resources in the first commit?

It could work yes, but I'm not sure if it makes sense to do it via the `PluginZip` and `PluginJar` classes? The point of the files is that they should explicitly come from the parent class loader and nothing else.

**Comment by slovdahl** [comment]
I removed the static files and use a static `@BeforeAll` method to create the files, please re-review.

**Comment by decebals** [comment]
Good job. Thanks!

**Pull request merged**
